# -*- coding: utf-8 -*-
"""Introduction-to-Scapy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fu5fZkofcV618n0f1dVPbvqHdy_yjlIJ

**Introduction to Scapy**
"""

pip install scapy

from scapy.all import *

packet = rdpcap('/content/crack-02.cap')

packet

p= packet[0]

p.show()

p=packet[3]

p.show()

p = IP()/TCP() #defines a new packet

p.show()

p[TCP].dport=8080 
#switches http to http_at

p.show()

p = IP(dst="8.8.8.8")/TCP(dport=53)
# packet creation + modification

p.show()

p = IP(dst="8.8.8.8")/UDP(dport=53)/DNS()
# upd packet containing a dns packet

p.show()
#default udp packet created